version: "3.8"
services:
  traefik:
    image: "traefik:v2.10"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    # - "443:443" TODO - HTTPS Example using letsencrypt
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  default:
    name: proxy